[project]
name = "image-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lmdeploy>=0.9.2.post1",
    "torch>=2.1.0",
    "outlines<0.1.0",
]
